Repository kiblykat/TheReviewRoom, pull requests merged in 2024-03, with the labels that each got.

#3 (SIS-19) & (SIS-23): Added basic CI and basic test cases for testing the CI system.
  .github/workflows/CI.yml
  src/main/java/sg/com/smartinventory/DataLoader.java
  src/main/java/sg/com/smartinventory/SmartInventoryApplication.java
  src/main/java/sg/com/smartinventory/controllers/CustomerController.java
  src/main/java/sg/com/smartinventory/entity/Customer.java
  src/main/java/sg/com/smartinventory/entity/Product.java
  src/main/java/sg/com/smartinventory/entity/Review.java
  src/main/java/sg/com/smartinventory/repository/CustomerRepository.java
  src/main/java/sg/com/smartinventory/repository/ProductRepository.java
  src/main/java/sg/com/smartinventory/repository/ReviewRepository.java
  src/main/java/sg/com/smartinventory/serviceImpls/CustomerServiceImpl.java
  src/main/java/sg/com/smartinventory/services/CustomerService.java
  src/test/java/sg/com/smartinventory/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/CustomerServiceImplTest.java
  src/test/java/sg/com/smartinventory/SmartInventoryApplicationTests.java
Labels: enhancement

#4 SIS-22: Updated ER Diagram.
  Documentation/Diagrams/Entity Relationship Diagram.md
  src/main/java/sg/com/smartinventory/DataLoader.java
  src/main/java/sg/com/smartinventory/controllers/CustomerController.java
  src/main/java/sg/com/smartinventory/entities/Customer.java
  src/main/java/sg/com/smartinventory/entities/Product.java
  src/main/java/sg/com/smartinventory/entities/Review.java
  src/main/java/sg/com/smartinventory/repositories/CustomerRepository.java
  src/main/java/sg/com/smartinventory/repositories/ProductRepository.java
  src/main/java/sg/com/smartinventory/repositories/ReviewRepository.java
  src/main/java/sg/com/smartinventory/serviceImpls/CustomerServiceImpl.java
  src/main/java/sg/com/smartinventory/services/CustomerService.java
  src/test/java/sg/com/smartinventory/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/CustomerServiceImplTest.java
  src/test/java/sg/com/smartinventory/SmartInventoryApplicationTests.java
Labels: enhancement

#5 SIS-23: Updated CI to generate and save test reports
  .github/workflows/CI.yml
  pom.xml
  src/main/resources/application.properties
Labels: enhancement

#8 SIS-22 & SIS-30: Removed the invalid duplicate foreign keys based on the updated ER diagram and added Spring Boot profiles support
  Documentation/Diagrams/Entity Relationship Diagram.md
  src/main/java/sg/com/smartinventory/SmartInventoryApplication.java
  src/main/java/sg/com/smartinventory/entities/Customer.java
  src/main/java/sg/com/smartinventory/entities/Product.java
  src/main/java/sg/com/smartinventory/entities/Review.java
  src/main/java/sg/com/smartinventory/utility/DataLoader.java
  src/main/resources/application.properties
  src/main/resources/logback-spring.xml
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ProductControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/integration/IntegrationTest.java
  src/test/java/sg/com/smartinventory/services/CustomerServiceImplTest.java
  src/test/java/sg/com/smartinventory/services/ProductServiceImplTest.java
  src/test/java/sg/com/smartinventory/services/ReviewServiceImplTest.java
  src/test/java/sg/com/smartinventory/useCases/UseCaseTest.java
  src/test/resources/application-logging-test.properties
  src/test/resources/logback-test.xml
Labels: enhancement

#9 SIS-22: Updated ER Diagram to change mobile_no to phone_no
  Documentation/Diagrams/Entity Relationship Diagram.md
  src/main/java/sg/com/smartinventory/entities/Customer.java
  src/main/java/sg/com/smartinventory/exceptions/ProductNotFoundException.java
  src/main/java/sg/com/smartinventory/exceptions/ReviewNotFoundException.java
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/integration/IntegrationTest.java
  src/test/java/sg/com/smartinventory/services/CustomerServiceImplTest.java
  src/test/java/sg/com/smartinventory/useCases/UseCaseTest.java
Labels: enhancement

#10 SIS-27: Created Endpoints For The Review Entity
  src/main/java/sg/com/smartinventory/controllers/CustomerController.java
  src/main/java/sg/com/smartinventory/controllers/ReviewController.java
  src/main/java/sg/com/smartinventory/entities/Customer.java
  src/main/java/sg/com/smartinventory/entities/Product.java
  src/main/java/sg/com/smartinventory/entities/Review.java
  src/main/java/sg/com/smartinventory/repositories/CustomerRepository.java
  src/main/java/sg/com/smartinventory/repositories/ProductRepository.java
  src/main/java/sg/com/smartinventory/repositories/ReviewRepository.java
  src/main/java/sg/com/smartinventory/serviceImpls/CustomerServiceImpl.java
  src/main/java/sg/com/smartinventory/serviceImpls/ReviewServiceImpl.java
  src/main/java/sg/com/smartinventory/services/CustomerService.java
  src/main/java/sg/com/smartinventory/services/ReviewService.java
  src/main/java/sg/com/smartinventory/utility/DataLoader.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/services/ReviewServiceImplTest.java
Labels: enhancement

#11 SIS-27 & SIS-29: Added Basic CRUD for Customer And Product
  pom.xml
  src/main/java/sg/com/smartinventory/serviceImpls/CustomerServiceImpl.java
  src/main/java/sg/com/smartinventory/serviceImpls/ProductServiceImpl.java
  src/main/java/sg/com/smartinventory/services/CustomerService.java
  src/main/java/sg/com/smartinventory/services/ProductService.java
Labels: enhancement

#12 Added security management and user management related sample files.
  pom.xml
  src/main/java/sg/com/smartinventory/controllers/AuthController.java.dev
  src/main/java/sg/com/smartinventory/controllers/GlobalExceptionHandler.java.dev
  src/main/java/sg/com/smartinventory/controllers/UserController.java.dev
  src/main/java/sg/com/smartinventory/controllers/UserRoleController.java.dev
  src/main/java/sg/com/smartinventory/entities/ErrorResponse.java.dev
  src/main/java/sg/com/smartinventory/entities/User.java.dev
  src/main/java/sg/com/smartinventory/entities/UserRole.java.dev
  src/main/java/sg/com/smartinventory/exceptions/GlobalExceptionHandler.java.dev
  src/main/java/sg/com/smartinventory/exceptions/UserNotFoundException.java.dev
  src/main/java/sg/com/smartinventory/exceptions/UserRoleNotFoundException.java.dev
  src/main/java/sg/com/smartinventory/repositories/UserRepository.java.dev
  src/main/java/sg/com/smartinventory/repositories/UserRoleRepository.java.dev
  src/main/java/sg/com/smartinventory/security/JwtTokenFilter.java.dev
  src/main/java/sg/com/smartinventory/security/JwtTokenUtil.java.dev
  src/main/java/sg/com/smartinventory/security/SecurityConfiguration.java.dev
  src/main/java/sg/com/smartinventory/serviceImpls/CustomUserDetailsService.java.dev
  src/main/java/sg/com/smartinventory/serviceImpls/UserDataLoader.java.dev
  src/main/java/sg/com/smartinventory/serviceImpls/UserRoleServiceImpl.java.dev
  src/main/java/sg/com/smartinventory/serviceImpls/UserServiceImpl.java.dev
  src/main/java/sg/com/smartinventory/services/UserRoleService.java.dev
  src/main/java/sg/com/smartinventory/services/UserService.java.dev
  src/main/resources/application.properties
  src/test/java/sg/com/smartinventory/entities/ErrorResponseTest.java
Labels: documentation, enhancement, help wanted

#13 Fixed issue throwing exception.
  src/main/java/sg/com/smartinventory/repositories/CustomerRepository.java
  src/main/java/sg/com/smartinventory/repositories/ProductRepository.java
  src/main/java/sg/com/smartinventory/repositories/ReviewRepository.java
  src/main/java/sg/com/smartinventory/serviceImpls/CustomerServiceImpl.java
  src/main/java/sg/com/smartinventory/serviceImpls/ProductServiceImpl.java
  src/main/java/sg/com/smartinventory/serviceImpls/ReviewServiceImpl.java
  src/main/java/sg/com/smartinventory/services/CustomerService.java
  src/main/java/sg/com/smartinventory/services/ProductService.java
  src/main/java/sg/com/smartinventory/services/ReviewService.java
Labels: bug, enhancement

#14 Added testing boilerplate code and Utility classes.
  src/main/java/sg/com/smartinventory/utility/Utility.java
  src/test/java/sg/com/smartinventory/SmartInventoryApplicationTests.java
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ProductControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/entities/CustomerTest.java
  src/test/java/sg/com/smartinventory/entities/ErrorResponseTest.java
  src/test/java/sg/com/smartinventory/entities/ProductTest.java
  src/test/java/sg/com/smartinventory/entities/ReviewTest.java
  src/test/java/sg/com/smartinventory/integration/IntegrationTest.java
  src/test/java/sg/com/smartinventory/services/CustomerServiceImplTest.java
  src/test/java/sg/com/smartinventory/services/ProductServiceImplTest.java
  src/test/java/sg/com/smartinventory/services/ReviewServiceImplTest.java
  src/test/java/sg/com/smartinventory/useCases/UseCaseTest.java
  src/test/java/sg/com/smartinventory/utility/DataLoaderTest.java
  src/test/java/sg/com/smartinventory/utility/Utility.java
Labels: enhancement

#18 Added skeleton for test case setup and cleanup.
  src/main/java/sg/com/smartinventory/utility/DataLoader.java
  src/test/java/sg/com/smartinventory/SmartInventoryApplicationTests.java
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ProductControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/entities/CustomerTest.java
  src/test/java/sg/com/smartinventory/entities/ErrorResponseTest.java
  src/test/java/sg/com/smartinventory/entities/ProductTest.java
  src/test/java/sg/com/smartinventory/entities/ReviewTest.java
  src/test/java/sg/com/smartinventory/integration/IntegrationTest.java
  src/test/java/sg/com/smartinventory/services/CustomerServiceImplTest.java
  src/test/java/sg/com/smartinventory/services/ProductServiceImplTest.java
  src/test/java/sg/com/smartinventory/services/ReviewServiceImplTest.java
  src/test/java/sg/com/smartinventory/useCases/UseCaseTest.java
  src/test/java/sg/com/smartinventory/utility/DataLoaderTest.java
Labels: enhancement

#21 SIS-28 completed
  ThunderClient/EndpointTests.json
  src/main/java/sg/com/smartinventory/controllers/ProductController.java
  src/main/java/sg/com/smartinventory/repositories/ProductRepository.java
  src/main/java/sg/com/smartinventory/serviceImpls/ProductServiceImpl.java
  src/main/java/sg/com/smartinventory/services/ProductService.java
Labels: enhancement

#23 SiS-41
  ThunderClient/EndpointTests.json
  src/main/java/sg/com/smartinventory/controllers/ReviewController.java
  src/main/java/sg/com/smartinventory/serviceImpls/ReviewServiceImpl.java
Labels: bug

#24 SIS-24: Added test print.
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ProductControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/integration/IntegrationTest.java
  src/test/java/sg/com/smartinventory/useCases/UseCaseTest.java
Labels: enhancement

#25 SIS-41, added search review endpoints
  ThunderClient/EndpointTests.json
  src/main/java/sg/com/smartinventory/controllers/ReviewController.java
  src/main/java/sg/com/smartinventory/entities/Customer.java
  src/main/java/sg/com/smartinventory/serviceImpls/ReviewServiceImpl.java
Labels: enhancement

#26 SIS-24: Added dirties context for integration test cases.
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ProductControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/integration/IntegrationTest.java
  src/test/java/sg/com/smartinventory/useCases/UseCaseTest.java
Labels: enhancement

#27 Create Test DataLoader.java
  src/main/java/sg/com/smartinventory/controllers/ReviewController.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
  src/test/java/sg/com/smartinventory/utility/DataLoader.java
Labels: bug, enhancement

#28 SIS-24: Added test cases
  src/test/java/sg/com/smartinventory/controllers/CustomerControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ProductControllerTest.java
  src/test/java/sg/com/smartinventory/controllers/ReviewControllerTest.java
Labels: enhancement
